name: epimodel

# later change to something else?
on: [tag]

env:
  IMAGE_NAME: epimodel

## NONE OF THE BELOW HAS BEEN WORKING
## just copied from covid
jobs:
  setup-build-publish-deploy:
    if: github.ref == 'refs/heads/master'
    name: Build, Publish, Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build
      run: |
        docker build -t gcr.io/epidemics-270907/$IMAGE_NAME .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |
        docker push gcr.io/epidemics-270907/$IMAGE_NAME

    - name: Helm deploy [PRODUCTION (master branch)]
      uses: hahow/install-helm-chart-action@v1.0.0
      with:
        gcloud_auth_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        gcloud_project_id: ${{ secrets.GKE_PROJECT }}
        cluster_name: epidemics
        cluster_region: us-west1-c
        release_namespace: production
        release_name: covid
        chart_name: ./deploy/chart
        helm_upgrade_args: |
          --values ./deploy/chart/values.yaml
          --set imageName=gcr.io/TBD!!!
          --debug

